version: '3.8'

services:
  # Postgres Master
  pg-1: &pg
    image: 'bitnami/postgresql-repmgr:latest'
    networks:
      - postgres-network
    volumes:
      - pg_data:/bitnami/postgresql
    env_file: .env_postgres
    deploy: &swarm-01
      placement:
        constraints:
          - node.hostname == swarm-01

  etcd1: &etcd
    image: quay.io/coreos/etcd:v3.5.8
    hostname: etcd1
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_NAME=etcd1
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd1:2380
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd1:2379
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster
      - ETCD_INITIAL_CLUSTER=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
      - ETCD_INITIAL_CLUSTER_STATE=new
    deploy:
      <<: *swarm-01
    networks:
      - postgres-network

  # Postgres Node2
  pg-2:
    <<: *pg
    volumes:
      - pg_data:/bitnami/postgresql
    environment:
      - REPMGR_NODE_NAME=pg-2
      - REPMGR_NODE_NETWORK_NAME=pg-2
    deploy: &swarm-02
      placement:
        constraints:
          - node.hostname == swarm-02

  etcd2:
    <<: *etcd
    hostname: etcd2
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_NAME=etcd2
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd2:2380
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd2:2379
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster
      - ETCD_INITIAL_CLUSTER=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
      - ETCD_INITIAL_CLUSTER_STATE=new
    deploy:
      <<: *swarm-02

  # Postgres Node3
  pg-3:
    <<: *pg
    volumes:
      - pg_data:/bitnami/postgresql
    environment:
      - REPMGR_NODE_NAME=pg-3
      - REPMGR_NODE_NETWORK_NAME=pg-3
    deploy: &swarm-03
      placement:
        constraints:
          - node.hostname == swarm-03

  etcd3:
    <<: *etcd
    hostname: etcd3
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_NAME=etcd3
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd3:2380
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd3:2379
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster
      - ETCD_INITIAL_CLUSTER=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
      - ETCD_INITIAL_CLUSTER_STATE=new
    deploy:
      <<: *swarm-03

  pgpool:
    image: docker.io/bitnami/pgpool
    ports:
      - 5432:5432
    env_file: .env_postgres
    deploy: &swarm-01
      replicas: 3
    healthcheck:
      test: ["CMD", "/opt/bitnami/scripts/pgpool/healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - postgres-network

networks:
  postgres-network:
    external: true

volumes:
  pg_data:
    driver: local

