version: '3.8'

services:
  etcd:
    image: docker.io/bitnami/etcd:3
    hostname: etcd{{.Task.Slot}}
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_NAME=etcd{{.Task.Slot}}
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd{{.Task.Slot}}:2380
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd{{.Task.Slot}}:2379
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster
      - ETCD_INITIAL_CLUSTER=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
      - ETCD_INITIAL_CLUSTER_STATE=new
    deploy:
      replicas: 3
      placement:
        max_replicas_per_node: 1
    networks:
      - etcd-network
#    healthcheck: &healthcheck
#      test: ["CMD", "etcdctl", "--endpoints=http://127.0.0.1:2379", "endpoint", "health"]
#      interval: 30s
#      timeout: 10s
#      retries: 3

  debug:
    image: alpine
    command: sh -c "sleep 1d" # Запустите контейнер на 1 день, затем он будет остановлен.
    networks:
      - etcd-network
    deploy:
      placement:
        constraints:
          - node.hostname == swarm-01

networks:
  etcd-network:
    driver: overlay
