- name: "Provision Docker Swarm Cluster"
  become: true
  hosts: all
  roles:
    - role: HanXHX.debian_bootstrap
      vars:
        dbs_hostname: "{{ inventory_hostname }}"
        dbs_alternative_editor: /usr/bin/nano
        dbs_users: ['devops']
        dbs_groups: ['devops']
    - role: atosatto.docker-swarm
    - role: geerlingguy.security
      vars:
        security_ssh_port: 15122
        security_ssh_allowed_users:
          - devops
        security_sudoers_passwordless:
          - devops
    - role: geerlingguy.glusterfs